### ISSUE TITLE
gRPC 추가

### ISSUE THREAD

**Issue by chacham** [frozen-dumplings/wallaby#1]
- gRPC 커맨드라인으로는 되는데, 웹에서는 안된다
- 웹에서 http/2 관련 문제로 아직은 안됨
  - proxy를 추가해서 해볼 것
- 참고
  - https://github.com/grpc/grpc-web
  - https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/grpc_bridge
  - https://github.com/envoyproxy/envoy/tree/master/examples/grpc-bridge

**Comment by chacham** [comment]
앱으로는 되는것 확인
- 웹이랑 네이티브에서 grpc 쓰는걸 분리해서 import해야 할 듯
- 웹은 proxy 거치고, 네이티브는 직접

**Comment by chacham** [comment]
아니면, 웹에서는 flutter 포기하고 따로 만드는 방법이 더 나을 수도 있을듯
- websocket 써서 연결

**Comment by cosmicb0y** [comment]
> * gRPC 커맨드라인으로는 되는데, 웹에서는 안된다
> * 웹에서 http/2 관련 문제로 아직은 안됨
>   
>   * proxy를 추가해서 해볼 것
> * 참고
>   
>   * https://github.com/grpc/grpc-web
>   * https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/grpc_bridge
>   * https://github.com/envoyproxy/envoy/tree/master/examples/grpc-bridge

브라우저 지원이 필요한거면 언제 프록시없이 쓸 수 있는거지

**Comment by cosmicb0y** [comment]
> 아니면, 웹에서는 flutter 포기하고 따로 만드는 방법이 더 나을 수도 있을듯
> 
> * websocket 써서 연결

개인적으로는 방식 나뉘는 것보단 proxy 거치더라도 같은 방식으로 하면 좋겠음

**Comment by chacham** [comment]
> > * gRPC 커맨드라인으로는 되는데, 웹에서는 안된다
> > * 웹에서 http/2 관련 문제로 아직은 안됨
> >   
> >   * proxy를 추가해서 해볼 것
> > * 참고
> >   
> >   * https://github.com/grpc/grpc-web
> >   * https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/grpc_bridge
> >   * https://github.com/envoyproxy/envoy/tree/master/examples/grpc-bridge
> 
> 브라우저 지원이 필요한거면 언제 프록시없이 쓸 수 있는거지

고건잘모르겠다
gRPC가 http2베이스인데, protocol buffer란걸로 감싸서 바이너리로 주고받는 형식이거든
그걸 중간에서 http1.1로 통역해주는애가 필요한듯.
Http2가 브라우저에선 1.1로 핸드쉐이킹하는게 하위호환성때문에 필요해서 그런것같다

**Comment by chacham** [comment]
> > 아니면, 웹에서는 flutter 포기하고 따로 만드는 방법이 더 나을 수도 있을듯
> > 
> > * websocket 써서 연결
> 
> 개인적으로는 방식 나뉘는 것보단 proxy 거치더라도 같은 방식으로 하면 좋겠음

나도 고렇게생각한다
코드쪼개서 두번개발하는것보단 프록시세우는게 나을듯

**Comment by chacham** [comment]
proxy는 도커로 슥삭하면 될것같으니, 나중에 시간있을 때 해볼 것

**Comment by chacham** [comment]
> * gRPC 커맨드라인으로는 되는데, 웹에서는 안된다
> * 웹에서 http/2 관련 문제로 아직은 안됨
>   
>   * proxy를 추가해서 해볼 것
> * 참고
>   
>   * https://github.com/grpc/grpc-web
>   * https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/grpc_bridge
>   * https://github.com/envoyproxy/envoy/tree/master/examples/grpc-bridge

web에서 안되는건 별도 issue로 등록
